name:                statum-metrics
version:             0.1.0.0
github:              "prasmussen/statum-metrics"
license:             BSD3
author:              "Petter Rasmussen"
maintainer:          "petter.rasmussen@gmail.com"
copyright:           "2019 Petter Rasmussen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/prasmussen/statum-metrics#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- attoparsec
- transformers
- either
- stm
- time
- clock
- safe
- safe-exceptions
- mtl
- disk-free-space
- aeson
- http-client
- http-client-tls
- http-types

default-extensions:
- OverloadedStrings
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- TypeSynonymInstances
- MultiParamTypeClasses
- FunctionalDependencies
- NoMonomorphismRestriction
- GADTs
- BangPatterns
- DeriveGeneric
- ScopedTypeVariables
- Strict

library:
  source-dirs: src

executables:
  statum-metrics:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - statum-metrics

tests:
  statum-metrics-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - statum-metrics
